libobj = miniglut.obj
testobj = test.obj
alib = miniglut.lib
bin = test.exe

CC = cl
LD = link
AR = lib

CFLAGS = -nologo -Zi
LDFLAGS = $(alib) user32.lib gdi32.lib opengl32.lib winmm.lib

$(bin): $(testobj) $(alib)
	$(LD) -nologo -out:$@ $(testobj) $(LDFLAGS)

$(alib): $(libobj)
	$(AR) -nologo -out:$@ $(libobj)

clean:
	del $(libobj) $(testobj) $(bin) $(alib)
