name: Windows MinGW build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v3
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW32
        install: mingw-w64-i686-gcc mingw-w64-i686-make

    - name: build
      run: mingw32-make

    - name: package
      run: |
        mkdir miniglut-win32-mingw
        cp libminiglut-w32.a miniglut-win32-mingw/libminiglut.a
        cp test.exe miniglut-win32-mingw

    - uses: actions/upload-artifact@v4
      with:
        name: miniglut-win32-mingw
        path: miniglut-win32-mingw

# vi:ts=2 sts=2 sw=2:expandtab
